# DEV profili: yerel gelistirme (localhost servisleri).
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.etiya: DEBUG
